# itk-version: 2.2.0
version: "3"

services:
  phpfpm:
    environment:
      - PHP_SENDMAIL_PATH='/usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"'

  nginx:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=ITKBasicAuth@file"
      # Disable basic auth for api path (path is protected by auth token)
      # (The rule needs to have higher priority implicit by rule length or explicit via priority label than the basic auth rule).
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}BypassBasicAuth.rule=Host((`${COMPOSE_SERVER_DOMAIN}`) && PathPrefix(`/api/udstykning/`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"

  mailhog:
    image: itkdev/mailhog
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}-http.rule=Host(`mailhog.${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}.rule=Host(`mailhog.${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.services.mailhog_${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailhog_${COMPOSE_PROJECT_NAME}.middlewares=ITKMailhogAuth@file"
