<?php
/**
 * @file
 * @TODO: Missing documentation.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function grundsalg_plots_theme($existing, $type, $theme, $path) {
  return array(
    'grundsalg_plots' => array(
      'template' => 'grundsalg-plots',
      'variables' => array(
        'variables' => NULL,
      ),
    )
  );
}

/**
 * Implements hook_proprocess_node().
 */
function grundsalg_plots_preprocess_node(&$variables) {
  $path = '/' . drupal_get_path('module', 'grundsalg_plots') . '/js';

  // Add plots to subdivision.
  if (($variables['view_mode'] == 'full' && $variables['node']->getType() == 'subdivision')) {
    // Get sub-division id.
    $subdivision_id = $variables['node']->get('field_subdivision_id')->value;

    // Build render array to kick start the Angular part of plots.
    if (isset($subdivision_id)) {
      $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');
      $cache_ttl = $config->get('grundsalg_plots_cache');

      $variables['content']['plots'] = array(
        '#theme' => 'grundsalg_plots',
        '#type' => 'markup',
        '#attached' => array(
          'library' => array(
            'grundsalg_plots/show_plots',
            'grundsalg_plots/show_plots.services',
          ),
          'drupalSettings' => array(
            'grundsalg_plots' => array(
              'url' => _grundsalg_plots_get_url(),
              'template' => $path . '/templates/plots.html',
              'subdivision_id' => $subdivision_id,
              'cache_ttl' => isset($cache_ttl) ? $cache_ttl : 300,
            )
          )
        )
      );
    }
  }
  else {
    /**
     * @Hack: Make plotService available to Angular at all times or the
     *        mapsController will fail.
     */
    $variables['#attached']['library'][] = 'grundsalg_plots/show_plots.services';
    $variables['#attached']['drupalSettings'] = array(
      'grundsalg_plots' => array(
        'url' => _grundsalg_plots_get_url(),
        'template' => $path . '/templates/plots.html',
        'cache_ttl' => isset($cache_ttl) ? $cache_ttl : 300,
      )
    );
  }
}


/**
 * Implements hook_form_node_subdivision_edit_form_alter()
 *
 * Modify the plots field in node edit form to display the plots for given
 * sub-division.
 */
function grundsalg_plots_form_node_subdivision_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Create field wrapper to attach Angular to the edit form.
  $form['plots_wrapper'] = array(
    '#type' => 'details',
    '#title' => t('Plots'),
    '#open' => FALSE,
    '#weight' => 100,
    '#attributes' => array(
      'data-ng-app' => 'grundsalg',
    ),
  );

  // Move subdivision field into wrapper.
  $form['plots_wrapper']['field_subdivision_id'] = $form['field_subdivision_id'];
  unset($form['field_subdivision_id']);
  $form['plots_wrapper']['field_subdivision_id']['#weight'] = 0;

  // Get sub-division id.
  $entity = $form_state->getFormObject()->getEntity();
  $subdivision_id = $entity->get('field_subdivision_id')->value;

  $path = '/' . drupal_get_path('module', 'grundsalg_plots') . '/js';

  $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');
  $cache_ttl = $config->get('grundsalg_plots_cache');

  // Prepare angular templates.
  $plots = array(
    '#theme' => 'grundsalg_plots',
    '#type' => 'markup',
    '#attached' => array(
      'library' => array(
        'grundsalg_plots/show_plots',
        'grundsalg_plots/show_plots.services',
      ),
      'drupalSettings' => array(
        'grundsalg_plots' => array(
          'url' => _grundsalg_plots_get_url(),
          'template' => $path . '/templates/plots-form.html',
          'subdivision_id' => $subdivision_id,
          'cache_ttl' => isset($cache_ttl) ? $cache_ttl : 300,
        )
      )
    )
  );

  // Add Angular plots template to wrapper.
  $form['plots_wrapper']['plots'] = array(
    '#type' => 'item',
    '#description' => render($plots),
    '#weight' => 3,
  );
}

/**
 * Build URL to fetch plots data from base on configuration.
 *
 * @return string
 *   The URL to the plots data end-point.
 */
function _grundsalg_plots_get_url() {
  $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');

  // Find data end-point (note that %str% in the URL is replaced with the actual
  // ID in Angular).
  $url = $config->get('grundsalg_db_client_url') . '/udstykning/%subdivisionId%/grunde';
  if ($config->get('grundsalg_db_client_use_example_data')) {
    $url = '/' . $config->get('grundsalg_db_client_example_file');
  };

  return $url;
}