<?php

/**
 * Implements hook_proprocess_page().
 *
 * @TODO: Note this will load angular on all node pages. It should only be
 *        loaded on pages that needs it?
 */
function grundsalg_angular_preprocess_page(&$variables) {
  if (isset($variables['node'])) {
    // Load the AngularJS.
    $variables['#attached']['library'][] = 'grundsalg_angular/angular';

    // Defines the application tag that Angular will bootstrap.
    $variables['attributes']['data-ng-app'] = 'grundsalg';
  }
}

/**
 * Implements hook_js_alter().
 *
 * Search angular applications for drupal translations.
 */
function grundsalg_angular_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  $files = array();
  $path = 'modules/custom';

  // Files to scan for translations (js and templates).
  $extensions = Array( 'js', 'html' );

  // Find the files.
  $it = new RecursiveDirectoryIterator($path);
  foreach(new RecursiveIteratorIterator($it) as $file)  {
    $ext = pathinfo($file, PATHINFO_EXTENSION);
    if (in_array($ext, $extensions)) {
      $files[] = $file->getPathname();
    }
  }

  // Scan the files to get translations into the database.
  locale_js_translate($files);
}

