<?php
/**
 * @file
 * @TODO: Missing documentation!
 */

/**
 * Implements hook_proprocess_page().
 */
function grundsalg_maps_preprocess_page(&$variables) {
  // Add angular to certain node types.
  if (isset($variables['node'])) {
    $type = $variables['node']->bundle();
    if (in_array($type, array('subdivision', 'area', 'overview_page'))) {

      $variables['#attached']['library'][] = 'grundsalg_maps/openlayers';
      $variables['#attached']['library'][] = 'grundsalg_maps/angular';

      $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');
      $path = '/' . drupal_get_path('module', 'grundsalg_maps');

      $cache_ttl = $config->get('grundsalg_maps_areas_cache');

      $variables['#attached']['drupalSettings']['grundsalg_maps'] = array(
        'dir' => $path  . '/js',
        'url' => $config->get('grundsalg_maps_url'),
        'cache_ttl' => isset($cache_ttl) ? $cache_ttl : 300,
        'map_type' => $type,
      );

      switch ($type) {
        case 'overview_page':
          $config = array(
            'plot_type' => $variables['node']->get('field_plot_type')->target_id,
            'zoom' => array (
              'default' => 6,
              'min' => 1,
              'max' => 14,
            ),
            'popup' => array(
              'areas' => array(
                'template' => $path . '/js/templates/popup-areas.html',
                'marker' => $path . '/images/marker-icon.png',
              ),
              'industry' => array(
                'template' => $path . '/js/templates/popup-industry.html',
                'marker' => array(
                  'default' => $path . '/images/marker-icon.png',
                  '471110' => $path . '/images/marker-icon.png',
                  '471120' => $path . '/images/marker-icon.png',
                  '471130' => $path . '/images/marker-icon.png',
                ),
              ),
              'institution' => array(
                'template' => $path . '/js/templates/popup-institution.html',
                'marker' => array(
                  'default' => $path . '/images/marker-icon.png',
                  'dagtilbud' => $path . '/images/marker-icon.png',
                  'dagpleje' => $path . '/images/marker-icon.png',
                  'fritid' => $path . '/images/marker-icon.png',
                  'intinst' => $path . '/images/marker-icon.png',
                  'vuggestue' => $path . '/images/marker-icon.png',
                  'bornehave' => $path . '/images/marker-icon.png',
                  'specskole' => $path . '/images/marker-icon.png',
                  'skole' => $path . '/images/marker-icon.png',
                  'sfo' => $path . '/images/marker-icon.png',
                  'fu' => $path . '/images/marker-icon.png',
                  'privtilbud' => $path . '/images/marker-icon.png',
                  'tandplejen' => $path . '/images/marker-icon.png',
                  'privskole' => $path . '/images/marker-icon.png'
                ),
              ),
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;

        case 'subdivision':
          // Get sub-division id.
          $subdivision_id = $variables['node']->get('field_subdivision_id')->value;

          $config = array(
            'subdivision_id' => $subdivision_id,
            'zoom' => array (
              'default' => 14,
              'min' => 11,
              'max' => 14,
            ),
            'popup' => array(
              'plots' => array(
                'template' => $path . '/js/templates/popup-plot.html',
                'marker' => $path . '/images/marker-icon.png',
              ),
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;

          break;

        default:
          $config = array(
            'zoom' => array (
              'default' =>6,
              'min' => 1,
              'max' => 14,
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;
      }
    }
  }
}
