<?php
/**
 * @file
 * @TODO: Missing documentation!
 */

/**
 * Implements hook_proprocess_page().
 */
function grundsalg_maps_preprocess_page(&$variables) {
  // Add angular to certain node types.
  if (isset($variables['node'])) {
    $type = $variables['node']->bundle();

    // We have a special use of maps on the project page. So we match the pages
    // nid and give it the type project. It's important to note here that the
    // system also have the entity type project and that this is not the once
    // that need to display a map.
    if ($type == 'page' && $variables['node']->id() == 7) {
      $type = 'project';
    }

    if (in_array($type, array('subdivision', 'area', 'overview_page', 'project'))) {
      $variables['#attached']['library'][] = 'grundsalg_maps/openlayers';
      $variables['#attached']['library'][] = 'grundsalg_maps/angular';

      $config = \Drupal::getContainer()->get('itkore_admin.itkore_config');
      $path = '/' . drupal_get_path('module', 'grundsalg_maps');

      $cache_ttl = $config->get('grundsalg_maps_areas_cache');

      $variables['#attached']['drupalSettings']['grundsalg_maps'] = array(
        'dir' => $path  . '/js',
        'url' => $config->get('grundsalg_maps_url'),
        'cache_ttl' => isset($cache_ttl) ? $cache_ttl : 300,
        'map_type' => $type,
      );

      switch ($type) {
        case 'project':
          $config = array(
            'zoom' => array (
              'default' => 5,
              'min' => 5,
              'max' => 8,
            ),
            'extent' => [498874.409185, 6195308.93897, 651386.409185, 6253164.93897],
            'popup' => array(
              'projects' => array(
                'scale' => 1,
                'template' => $path . '/js/templates/popup-projects.html',
                'marker' => $path . '/images/marker-default.png',
              ),
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;

        case 'overview_page':
          $config = array(
            'plot_type' => $variables['node']->get('field_plot_type')->target_id,
            'zoom' => array (
              'default' => 5,
              'min' => 5,
              'max' => 8,
            ),
            'extent' => 'auto',
            'popup' => array(
              'areas' => array(
                'scale' => 1,
                'template' => $path . '/js/templates/popup-areas.html',
                'marker' => $path . '/images/marker-default.png',
              ),
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;

        case 'area':
          $config = array(
            'plot_type' => $variables['node']->get('field_plot_type')->target_id,
            'area_id' => $variables['node']->id(),
            'zoom' => array (
              'default' => 6,
              'min' => 6,
              'max' => 10,
            ),
            'extent' => [498874.409185, 6195308.93897, 651386.409185, 6253164.93897],
            'popup' => array(
              'subdivision'=> array(
                'scale' => 1,
                'template' => $path . '/js/templates/popup-subdivision.html',
                'marker' => $path . '/images/marker-default.png',
              ),
              'industry' => array(
                'template' => $path . '/js/templates/popup-industry.html',
                'marker' => array(
                  'scale' => 0.8,
                  'default' => $path . '/images/marker-store.png',
                  '471110' => $path . '/images/marker-store.png',
                  '471120' => $path . '/images/marker-store.png',
                  '471130' => $path . '/images/marker-store.png',
                ),
              ),
              'institution' => array(
                'template' => $path . '/js/templates/popup-institution.html',
                'marker' => array(
                  'scale' => 0.8,
                  'default' => $path . '/images/marker-childcare.png',
                  // Institutioner.
                  'dagtilbud' => $path . '/images/marker-childcare.png',
                  'dagpleje' => $path . '/images/marker-childcare.png',
                  'fritid' => $path . '/images/marker-childcare.png',
                  'intinst' => $path . '/images/marker-childcare.png',
                  'vuggestue' => $path . '/images/marker-childcare.png',
                  'bornehave' => $path . '/images/marker-childcare.png',
                  'fu' => $path . '/images/marker-childcare.png',
                  'privtilbud' => $path . '/images/marker-childcare.png',
                  // Skoler.
                  'specskole' => $path . '/images/marker-school.png',
                  'skole' => $path . '/images/marker-school.png',
                  'sfo' => $path . '/images/marker-school.png',
                  'tandplejen' => $path . '/images/marker-school.png',
                  'privskole' => $path . '/images/marker-school.png',
                ),
              ),
              'bus' => array(
                'scale' => 0.8,
                'template' => $path . '/js/templates/popup-industry.html',
                'marker' => $path . '/images/marker-busstop.png',
              ),
            ),
          );
          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;

        case 'subdivision':
          // Get sub-division id.
          $subdivision_id = $variables['node']->get('field_subdivision_id')->value;

          // Get center.
          $coordinates = $variables['node']->get('field_coordinate')->value;

          $default_center = null;
          if (!empty($coordinates)) {
            $coordinates = explode(',', str_replace(' ', '', $coordinates));

            // Transform the center to new projection that matches the map's.
            $proj4 = new \proj4php\Proj4php();
            $proj4->addDef('EPSG:25832', '+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs');
            $projTo = new \proj4php\Proj('EPSG:25832', $proj4);
            $projFrom = new \proj4php\Proj('EPSG:4326', $proj4);
            $pointSrc = new \proj4php\Point($coordinates[1], $coordinates[0], $projFrom);
            $pointDest = $proj4->transform($projTo, $pointSrc);

            $default_center = explode(' ', $pointDest->toShortString());
            $default_center = array((float) $default_center[0], (float) $default_center[1]) ;
          }

          $config = array(
            'subdivision_id' => $subdivision_id,
            'zoom' => array (
              'default' => 11,
              'min' => 11,
              'max' => 16,
            ),
            'extent' => [498874.409185, 6195308.93897, 651386.409185, 6253164.93897],
            'popup' => array(
              'plots' => array(
                'scale' => 0.8,
                'template' => $path . '/js/templates/popup-plot.html',
              ),
              'industry' => array(
                'template' => $path . '/js/templates/popup-industry.html',
                'marker' => array(
                  'scale' => 0.8,
                  'default' => $path . '/images/marker-store.png',
                  '471110' => $path . '/images/marker-store.png',
                  '471120' => $path . '/images/marker-store.png',
                  '471130' => $path . '/images/marker-store.png',
                ),
              ),
              'institution' => array(
                'template' => $path . '/js/templates/popup-institution.html',
                'marker' => array(
                  'scale' => 0.8,
                  'default' => $path . '/images/marker-childcare.png',
                  // Institutioner.
                  'dagtilbud' => $path . '/images/marker-childcare.png',
                  'dagpleje' => $path . '/images/marker-childcare.png',
                  'fritid' => $path . '/images/marker-childcare.png',
                  'intinst' => $path . '/images/marker-childcare.png',
                  'vuggestue' => $path . '/images/marker-childcare.png',
                  'bornehave' => $path . '/images/marker-childcare.png',
                  'fu' => $path . '/images/marker-childcare.png',
                  'privtilbud' => $path . '/images/marker-childcare.png',
                  // Skoler.
                  'specskole' => $path . '/images/marker-school.png',
                  'skole' => $path . '/images/marker-school.png',
                  'sfo' => $path . '/images/marker-school.png',
                  'tandplejen' => $path . '/images/marker-school.png',
                  'privskole' => $path . '/images/marker-school.png',
                ),
              ),
              'bus' => array(
                'scale' => 0.8,
                'template' => $path . '/js/templates/popup-industry.html',
                'marker' => $path . '/images/marker-busstop.png',
              ),
            ),
          );

          // Add default center if one exists. It's used to center the map
          // correctly when no plots exists.
          if ($default_center) {
            $config['center'] = $default_center;
          }

          $variables['#attached']['drupalSettings']['grundsalg_maps'] += $config;
          break;
      }
    }
  }
}
