<?php
/**
 * @file
 * @TODO: Missing documentation!
 */

/**
 * Implements hook_proprocess_page().
 *
 * Adds javascript libraries, configuration and services to the pages.
 */
function grundsalg_tabs_preprocess_page(&$variables) {
  if (isset($variables['node'])) {
    $variables['display_tabs'] = FALSE;

    $type = $variables['node']->bundle();
    if (($type == 'subdivision' || $type == 'area')) {
      $variables['map'] = TRUE;
      $variables['images'] = TRUE;
      $variables['video'] = TRUE;
      $variables['coordinates'] = TRUE;

      $variables['#attached']['library'][] = 'grundsalg_tabs/angular';
      $variables['#attached']['library'][] = 'grundsalg_tabs/googlemaps-api';


      $variables['#attached']['drupalSettings']['grundsalg_tabs'] = array(
        'app_dir' => '/' . drupal_get_path('module', 'grundsalg_tabs') . '/js',
      );

      // Enable tabs (See page--node.html.twig)
      $variables['display_tabs'] = TRUE;

      // If no images exists on current node (hide image tab). If images exists
      // they will be move into JS from the grundsalg_slideshow module.
      if (!isset($variables['node']->field_media_image->target_id)) {
        $variables['images'] = FALSE;
      }

      // Add video link to js.
      if (isset($variables['node']->field_video->value)) {
        $render_array = $variables['node']->field_video->view('default');

        $variables['#attached']['library'][] = 'itk_azure_video/azure-video';
        $variables['#attached']['drupalSettings']['grundsalg_tabs']['video'] = \Drupal::service('renderer')->renderRoot($render_array);
      }
      else {
        $variables['video'] = FALSE;
      }

      // Add coordinates to JS (here used for street-view).
      if (isset($variables['node']->field_streetview_coordinate->value)) {
        $coordinates_str = $variables['node']->field_streetview_coordinate->value;
        $coordinates = explode(',', str_replace(' ', '', $coordinates_str));
        $variables['#attached']['drupalSettings']['grundsalg_tabs']['coordinates'] = array(
          'full' => $coordinates_str,
          'lat' => $coordinates['0'],
          'lon' => $coordinates['1'],
        );
      }
      else {
        $variables['coordinates'] = FALSE;
      }
    }
  }
}


/**
 * Implements hook_proprocess_node().
 *
 * @TODO: Need comment about why this is needed. Would the above not do this?
 */
function grundsalg_tabs_preprocess_node(&$variables) {
  // Add angular to certain node types.
  $type = $variables['node']->bundle();
  if (($type == 'subdivision' || $type == 'area')) {
    $variables['display_tabs'] = TRUE;
    $variables['app_dir'] = drupal_get_path('module', 'grundsalg_tabs') . '/js';
  }
}
