<?php

use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_proprocess_page().
 */
function grundsalg_tabs_preprocess_page(&$variables) {
  // Add angular to certain node types.
  if (isset($variables['node'])) {
    $type = $variables['node']->bundle();
    if (($type == 'subdivision' || $type == 'area')) {
      $variables['#attached']['library'][] = 'grundsalg_tabs/angular';
      $variables['#attached']['library'][] = 'grundsalg_tabs/leaflet';
      $variables['#attached']['library'][] = 'grundsalg_tabs/leaflet-drupal';
      $variables['#attached']['drupalSettings'] = array(
        'variables' => array(
          'app_dir' => '/' . drupal_get_path('module', 'grundsalg_tabs') . '/js',
        ),
      );
      // Enable angular (See page--node.html.twig)
      $variables['angular'] = TRUE;

      // Enable tabs (See page--node.html.twig)
      $variables['display_tabs'] = TRUE;

      // Add image urls to js.
      $variables['#attached']['drupalSettings']['variables']['images'][] = array(
        'url' => ImageStyle::load('main_content')->buildUrl(File::load($variables['node']->get('field_main_image')->target_id)->getFileUri()),
        'alt' => $variables['node']->get('field_main_image')->alt,
      );

    }
  }
}


/**
 * Implements hook_proprocess_node().
 */
function grundsalg_tabs_preprocess_node(&$variables) {
  // Add angular to certain node types.
  $type = $variables['node']->bundle();
  if (($type == 'subdivision' || $type == 'area')) {
    $variables['display_tabs'] = TRUE;
    $variables['app_dir'] = drupal_get_path('module', 'grundsalg_tabs') . '/js';
  }
}