<?php

/**
 * Implements hook_node_presave().
 */

function grundsalg_reference_tree_node_presave(Drupal\Core\Entity\EntityInterface $node){
  // If content type is area and it's the first save of the node.
  if ($node->getType() == 'area' && is_null($node->original)) {

    // Get plot type
    $term_id = $node->get('field_plot_type')->target_id;

    // Get all overview pages
    $nids = \Drupal::entityQuery('node')->condition('type', 'overview_page')->execute();
    $nodes =  \Drupal\node\Entity\Node::loadMultiple($nids);

    // Look for overview pages with the same tag as our saved node.
    foreach ($nodes as $overview_page_node) {
      if ($overview_page_node->get('field_plot_type')->target_id == $term_id) {
        // Set reference to an overview page with the same tag. (There should be only one)
        $node->set('field_parent', $overview_page_node->id());
      }
    }
  }
}