<?php

use Drupal\media_entity\Entity;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_proprocess_page().
 */
function grundsalg_slideshow_preprocess_page(&$variables) {
  // Add angular to certain node types.
  if (isset($variables['node'])) {
    $type = $variables['node']->bundle();

    // Add slideshow app to page.
    if (($type != 'subdivision' && $type != 'area')) {

      // Provide module path to js.
      $variables['#attached']['drupalSettings'] = array(
        'variables' => array(
          'app_dir' => '/' . drupal_get_path('module', 'grundsalg_slideshow') . '/js',
        ),
      );

      // Add image urls and alt to js.
      if (isset($variables['node']->field_media_image->target_id)) {
        foreach ($variables['node']->get('field_media_image') as $key => $item) {
          $image_entity = \Drupal::entityTypeManager()->getStorage('media')->load($item->target_id);

          $variables['#attached']['drupalSettings']['variables']['images'][$key] = array(
            'url' => ImageStyle::load('main_content')->buildUrl(File::load($image_entity->get('field_itk_media_image_upload')->target_id)->getFileUri()),
            'alt' => $image_entity->get('field_itk_media_image_upload')->alt,
          );
        }
      }
      else {
        $variables['#attached']['drupalSettings']['variables']['images'] = FALSE;
      }
    }
  }
}