<?php
require_once __DIR__ . '/src/Client.php';
require_once __DIR__ . '/src/Collection.php';
require_once __DIR__ . '/src/Item/Item.php';

use Grundsalg\Client;

/**
 * Create a connection to the remote db.
 */
function grundsalg_db_client_create_connection() {
  $db_url = \Drupal::config('grundsalg_db')->get('url');
  $db_name = \Drupal::config('grundsalg_db')->get('name');
  $db_pass = \Drupal::config('grundsalg_db')->get('pass');

  if (!empty($db_url) && !empty($db_name) && !empty($db_pass)) {
    $obj = new Client($db_url, $db_name, $db_pass);
    return $obj;
  }
  else {
    throw new Exception('No db connection');
  }
}